# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: WatchGuard.MobileVPNwithSSLclient
PackageVersion: 12.7.2
PackageLocale: en-US
Publisher: WatchGuard
PackageName: Mobile VPN with SSL client
License: MIT License
Copyright: (c)2004-2021 WatchGuard Technologies, Inc.
ShortDescription: Mobile VPN with SSL client Setup
ManifestType: defaultLocale
ManifestVersion: 1.2.0

